name: Run Robot Tests and Send to Datadog

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install robotframework

      - name: Run Robot Tests (continua mesmo com erro)
        run: |
          robot -d results tests/ || true

      - name: Parse Robot Output to JSON
        run: |
          python3 parse_robot_output.py

      - name: Send results to Datadog
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        run: |
          curl -X POST "https://http-intake.logs.datadoghq.com/v1/input" \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: $DD_API_KEY" \
            -d @robot-results.json